name: Pinterest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  unsplash_client: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.2.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  firebase_storage: ^12.1.1
  firebase_core: ^3.2.0
  sqflite: ^2.3.3+1
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.2
  font_awesome_flutter: ^10.7.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Appicons/Assets.xcassets/AppIcon.appiconset/256.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/256.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:
  uses-material-design: true


